version: "2"
services:
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    volumes:
      - storage:/var/app/storage
    networks:
      - default

volumes:
  storage:

networks:
  default: