// Code generated by mockery v2.14.1. DO NOT EDIT.

package repository

import mock "github.com/stretchr/testify/mock"

// TextManagementInterface is an autogenerated mock type for the TextManagementInterface type
type TextManagementInterface struct {
	mock.Mock
}

// CheckFileExists provides a mock function with given fields: fileName
func (_m *TextManagementInterface) CheckFileExists(fileName string) bool {
	ret := _m.Called(fileName)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(fileName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Load provides a mock function with given fields: fileName
func (_m *TextManagementInterface) Load(fileName string) ([]byte, error) {
	ret := _m.Called(fileName)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(fileName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(fileName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: fileName, content
func (_m *TextManagementInterface) Save(fileName string, content string) error {
	ret := _m.Called(fileName, content)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(fileName, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewTextManagementInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewTextManagementInterface creates a new instance of TextManagementInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTextManagementInterface(t mockConstructorTestingTNewTextManagementInterface) *TextManagementInterface {
	mock := &TextManagementInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
